# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Jekyll-Boilerplate
email:              email@email.com
description:        "The description"
url:                "http://yourdomain.com"
baseurl:            ""                              # the subpath of your site, e.g. /blog/

twitter_username:   jekyllrb
github_username:    jekyll

markdown:           kramdown
permalink:          pretty

# Build settings
exclude:
  - package.json
  - node_modules
  - gulpfile.babel.js
  - README.md

source:             ./src
destination:        ./dist